# Generated by Django 5.0.6 on 2024-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memory_capacity',
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.JSONField(default=dict),
        ),
    ]
